name: "Infra Pipeline | Azure"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./iac

    env:
      BACKEND_STORAGE_RESOURCE_GROUP: UniAnchietaTF
      BACKEND_STORAGE_ACCOUNT_NAME: azuniachietatf
      BACKEND_STORAGE_CONTAINER_NAME: tfstate
      BACKEND_STATE_NAME: azunianchieta.tfstate
      ARM_TENANT_ID: c0457be8-0157-48c2-af49-b621fb3d2c99
      ARM_SUBSCRIPTION_ID: 563efcd7-bd1e-41de-b5c3-6950a9b7d863
      ARM_CLIENT_ID: 9ecfd250-fb3b-4687-87df-cbb7bcc0b6a1
      ARM_CLIENT_SECRET: Nb28Q~kmcj6oyCj19NWMCcNEmM0UaolrHYeBAdvj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -out azapp.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve azapp.tfplan